site_name: Big Earth Hacks 2020
theme: 
  name:   material
extra_css:
  - stylesheets/extra.css
nav:
  - Introduction: index.md
  - Workshop Overview: workshop.md
  - Planet's Platform: 
    - Getting An Account: account.md
    - Explorer: explorer.md
    - Orders: orders.md
    - Stories: stories.md
    - APIs: apis.md
  - Visualization and Analysis:
    - Google Earth Engine: earth_engine_intro.md
    - Demo Dataset: earth_engine_demo_data.md
    - Image Visualization: earth_engine_visualization.md
    - Image Collection Filtering: earth_engine_filter.md
    - NDVI Timeseries Plotting: earth_engine_ndvi_over_time.md
  - Hack The Planet: happy_hacking.md
markdown_extensions:
    - toc:
        baselevel: 2